name: Second Workflow

on: [workflow_dispatch]

env:
  SHARED_VAR: "Workflow 2 Variable"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        run: echo "SHARED_VAR in Second Workflow: $SHARED_VAR"
