# This is a basic workflow to help you get started with Actions

name: Variables Scope Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  demo-job:
    runs-on: ubuntu-latest

    env:
      MY_JOB_VARIABLE: "This is a job-level variable"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - name: Step with all variables
       env:
         MY_STEP_VARIABLE: "This is a step-level variable"
       run: |
        echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
        echo "Job Variable: $MY_JOB_VARIABLE"
        echo "Step Variable: $MY_STEP_VARIABLE"

     - name: Step without step-level variable
       run: |
        echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
        echo "Job Variable: $MY_JOB_VARIABLE"
        echo "Step Variable: $MY_STEP_VARIABLE (should be empty)"
